# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &config_project_defaults
  working_directory: ~/repo

orbs:
  aws-cli: circleci/aws-cli@0.1.20

executors:
  node_default:
    docker:
      - image: circleci/node:12.13.0

commands:
  configure_aws:
    description: "Sets up AWS profiles and configuration"
    steps:
      - aws-cli/setup:
          profile-name: highsugar
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
  install_python_pip:
    description: "Installs python and pip"
    steps:
      - run: python --version
      - run:
          name: Install Python
          working_directory: /tmp
          command: |
            sudo apt-get install build-essential checkinstall
            sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
            wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
            tar xvf Python-3.6.0.tar.xz
            cd Python-3.6.0/
            ./configure
            sudo make altinstall
            python --version
  test_build_frontend:
    description: "Installs, tests and builds the frontend"
    steps:
      - run:
          working_directory: ~/repo/frontend
          command: npm test
      - run:
          working_directory: ~/repo/frontend
          command: npm run build

jobs:
  backend:
    <<: *config_project_defaults
    executor: node_default
    steps:
      - configure_aws
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}-{{ .Branch }}-{{ checksum "backend/package-lock.json" }}-{{ checksum "backend/lambda-nodejs/package-lock.json" }}-{{ checksum "backend/lambda-python/package-lock.json" }}-{{ .Revision }}
            - v1-{{ arch }}-{{ .Branch }}-{{ checksum "backend/package-lock.json" }}-{{ checksum "backend/lambda-nodejs/package-lock.json" }}-{{ checksum "backend/lambda-python/package-lock.json" }}
            - v1-{{ arch }}-{{ .Branch }}
            - v1-{{ arch }}
      - run:
          working_directory: ~/repo/backend
          command: npm run install-all
      - save_cache:
          paths:
            - ~/repo/backend/node_modules
            - ~/repo/backend/lambda-nodejs/node_modules
            - ~/repo/backend/lambda-python/node_modules
          key: v1-{{ arch }}-{{ .Branch }}-{{ checksum "backend/package-lock.json" }}-{{ checksum "backend/lambda-nodejs/package-lock.json" }}-{{ checksum "backend/lambda-python/package-lock.json" }}-{{ .Revision }}
      - install_python_pip
      - run:
          working_directory: ~/repo/backend
          command: npm run deploy-all

  frontend:
    <<: *config_project_defaults
    executor: node_default
    steps:
      - configure_aws
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}-{{ .Revision }}
            - v1-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
            - v1-{{ arch }}-{{ .Branch }}
            - v1-{{ arch }}
      - run:
          working_directory: ~/repo/frontend
          command: npm install
      - save_cache:
          paths:
            - ~/repo/frontend/node_modules
          key: v1-{{ arch }}-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}-{{ .Revision }}
      - test_build_frontend
      - run:
          working_directory: ~/repo/frontend
          command: npm run deploy
      - run:
          working_directory: ~/repo/frontend
          command: npm run domain

workflows:
  version: 2
  master_flow:
    jobs:
      - backend:
          filters:
            branches:
              only:
                - master
      - frontend:
          filters:
            branches:
              only:
                - master
