service: prolyzer-lambda-python

provider:
  name: aws
  runtime: python3.6
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  # See link for more information:
  #     https://serverless.com/framework/docs/providers/aws/guide/credentials/
  stage: ${{opt:stage, self:custom.defaultStage}}
  region: ${{opt:region, self:custom.defaultRegion}}
  profile: ${{opt:aws-profile, self:custom.profiles.${{self:provider.stage}}}}
  # See link for more information:
  #     https://serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions
  environment:
    NODE_ENV: ${{self:provider.stage}}
    STACK_PREFIX: ${{self:service}}-${{self:provider.stage}}

plugins:
  - serverless-iam-roles-per-function
  - serverless-cloudformation-changesets
  - serverless-python-requirements

functions:
  helloWorldPython:
    name: ${{self:service}}-${{self:provider.stage}}-helloWorld
    description: 'Hello World for Python'
    handler: src/helloWorld.handler
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: helloWorld
          method: get
  prolyzerPython:
    name: ${{self:service}}-${{self:provider.stage}}-prolyzer
    description: 'Prolyzer for Python'
    handler: src/prolyzer.handler
    timeout: 30
    memorySize: 128
    events:
      - http:
         path: prolyzer
         method: get

custom:
  # Custom staging profiles. You may access or modify these credentials in ~/.aws/credentials
  # See link for credentials documentation:
  #     https://serverless.com/framework/docs/providers/aws/guide/credentials/
  defaultStage: production
  defaultRegion: ap-southeast-1
  profiles:
    production: highsugar
    development: highsugar

  accountId: ${AWS::AccountId}

  pythonRequirements:
    dockerizePip: non-linux
